### PR TITLE
Update to latest OrbitDB (WIP)

### PR DESCRIPTION
**Pull request by haadcode**
***Work in progress***

This PR will update orbit-core to use the latest OrbitDB and IPFS. 

It's a big change since this codebase hasn't been worked on in months.

### CODE REVIEW

**Comment by haadcode** [comment]
Closes #15.

**Comment by haadcode** [comment]
Test version: https://ipfs.io/ipfs/QmNzQaPoK9gmq9du6R3KcGNJRKvkjuf7MpgYV5qFVr16gt. Built from https://github.com/orbitdb/orbit-web/pull/16/commits/88c4342c4824aa8f1c0c6df6c27318cf675c14ba.

**Comment by divyansheccentric** [comment]
Whenever I upload an image , its not shown after being uploaded . All I see is a 'loading' label like in the image below

38033305-65bd1020-32bd-11e8-891a-27823c8f6260

--> When I click on open image it shows a blank ipfs page
--> When I click the download button , it downloads an html file instead of image

...more info : When I checked the console, it showed this error ...

38033518-d665394c-32bd-11e8-8e1f-b0e17982932f


Please help. I don't know what's wrong here @haadcode

**Comment by diasdavid** [comment]
Can't wait for the day :)

**Comment by latenssi** [comment]
PR #36 will make this obsolete. Closing this PR.

**Pull request closed without merging**
